name: ic_scanner
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  localstorage: ^4.0.1+4
  file_picker: ^8.0.0+1
  phosphor_flutter: ^2.0.1
  image: ^4.1.7
  http: ^1.2.1
  crop_your_image: ^1.0.2
  dio: ^5.4.3+1
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
